// <auto-generated />
namespace MultipleTenancyAzureAD.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addjobdescriptioncreatedtimecreatedbyupdatedtimetotasktable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addjobdescriptioncreatedtimecreatedbyupdatedtimetotasktable));
        
        string IMigrationMetadata.Id
        {
            get { return "202202240819214_add jobdescription, createdtime, createdby, updatedtime to task table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
